"""Type stubs for the multi_demangle extension module."""

from collections.abc import Iterable
from typing import Any

class DemangleOptions:
    def __init__(
        self,
        *,
        return_type: bool = ...,
        parameters: bool = ...,
        normalize: bool = ...,
    ) -> None: ...
    @staticmethod
    def complete() -> DemangleOptions: ...
    @staticmethod
    def name_only() -> DemangleOptions: ...

class Normalizer:
    def normalize(self, mangled: str) -> str: ...
    @staticmethod
    def display() -> Normalizer: ...
    @staticmethod
    def matching() -> Normalizer: ...

def demangle_symbol(mangled: str, options: DemangleOptions | None = ...) -> str: ...
def demangle_symbols(
    symbols: Iterable[str],
    options: DemangleOptions | None = ...,
    *,
    unique: bool = ...,
) -> list[str]: ...
def demangle_symbol_ex(
    mangled: str, options: DemangleOptions | None = ...
) -> dict[str, Any]: ...
def classify_symbol(mangled: str) -> dict[str, Any]: ...
def detect_language(mangled: str) -> str | None: ...
def looks_mangled(mangled: str) -> bool: ...
def normalize_symbol(mangled: str, normalizer: Normalizer | None = ...) -> str: ...
