"""Type stubs for the multi_demangle extension module."""

from collections.abc import Iterable
from typing import Any

class DemangleOptions:
    def __init__(
        self,
        *,
        return_type: bool = ...,
        parameters: bool = ...,
        normalize: bool = ...,
    ) -> None: ...
    @staticmethod
    def complete() -> DemangleOptions: ...
    @staticmethod
    def name_only() -> DemangleOptions: ...

class Normalizer:
    def normalize(self, mangled: str) -> str: ...
    @staticmethod
    def display() -> Normalizer: ...
    @staticmethod
    def matching() -> Normalizer: ...

class DemangledInfo:
    @property
    def language(self) -> str | None: ...
    @property
    def display(self) -> str: ...
    @property
    def simple(self) -> str: ...
    @property
    def namespace(self) -> list[str]: ...
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def class_method(self) -> bool | None: ...
    @property
    def parameters(self) -> list[str] | None: ...
    @property
    def return_type(self) -> str | None: ...
    @property
    def hash(self) -> str | None: ...
    @property
    def template_args(self) -> list[str] | None: ...
    @property
    def is_generic(self) -> bool: ...
    @property
    def mangled(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

def demangle_symbol(mangled: str, options: DemangleOptions | None = ...) -> str: ...
def demangle_symbols(
    symbols: Iterable[str],
    options: DemangleOptions | None = ...,
    *,
    unique: bool = ...,
) -> list[str]: ...
def demangle_symbol_ex(
    mangled: str, options: DemangleOptions | None = ...
) -> dict[str, Any]: ...
def demangle_symbol_structured(
    mangled: str, options: DemangleOptions | None = ...
) -> DemangledInfo | None: ...
def classify_symbol(mangled: str) -> dict[str, Any]: ...
def detect_language(mangled: str) -> str | None: ...
def looks_mangled(mangled: str) -> bool: ...
def normalize_symbol(mangled: str, normalizer: Normalizer | None = ...) -> str: ...
